twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        app_name: 'PHP Todo App'
        app_version: '1.0.0'

when@test:
    twig:
        strict_variables: true
